### ISSUE TITLE
How to use remotipart with Webpacker gem

### ISSUE THREAD

**Issue by cdhagmann** [jbox-web/remotipart#1]

**Comment by n-rodriguez** [comment]
Copy [jquery.iframe-transport.js](https://github.com/jbox-web/remotipart/blob/master/vendor/assets/javascripts/jquery.iframe-transport.js) and [jquery.remotipart.js](https://github.com/jbox-web/remotipart/blob/master/vendor/assets/javascripts/jquery.remotipart.js) somewhere in `app/javascript` (depending on your directory tree) and require it in your pack :

```js
# Load JQuery Remotipart
require 'remotipart/jquery.iframe-transport.js'
require 'remotipart/jquery.remotipart.js'
```
